categories:
  medical:
    "(医療|病院|医療機関|診療|看護|高齢者|介護|ケア)": 3.0
    "(医療DX|電子カルテ|PHR|EHR|地域医療|救急|臨床)": 2.0

  care:
    "(介護|看護|高齢者|ケア|介護施設|訪問介護|訪問看護|地域包括)": 3.0
    "(働き方|働く|人材|研修|リスキリング)": 1.5

  dx:
    "(AI|IT|DX|デジタル|ICT|RPA|データ連携|API)": 2.0
    "(働き方|働く|生産性)": 1.2

  other:
    ".*": 0.0